name: merge dev to main
env:
  USER_NAME: roujiawang
  USER_EMAIL: rjwang@umich.edu
  PUSH_TOKEN: ${{secrets.SECRET_TOKEN}}
on:
  push:
    branches:
      - develop
jobs:
  merge-dev-to-main:
    runs-on: ubuntu-latest
    # You may pin to the exact commit or the version.
    # uses: bambamboole/gha-upmerge@de87b212278009f9ace0ba024701890b9eb3281b
    # Automatically up merge changes from one branch to another
    steps:
      - uses: actions/checkout@v1
      
      - uses: bambamboole/gha-upmerge@v1.0.1
        with:
          from_branch: develop
          to_branch: main
          user_name: USER_NAME
          user_email: USER_EMAIL
          push_token: PUSH_TOKEN
