name: Sync pushed develop branch to main
on:
  push:
    branches:
      - develop
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge develop -> main
        run: |
          git checkout main
          git merge develop
