name: Merge Branch dev to main
on:
  push:
    branches:
      - develop
permissions:
  contents: write
  issues: write
jobs:
  merge-branch-dev-to-main:
    name: Merge the develop branch into main
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.SECRET_TOKEN}}
      REPORT_AUTHOR: dependabot[bot]
      REPORT_LABEL: merge dev branch to main
    steps:
      - name: enable auto merge on mergebot
        uses: roujiawang/enable-automerge-action@v1
        with:
          github-token: ${{secrets.SECRET_TOKEN}}
          allowed-author: "dependabot[bot]"
          merge-method: MERGE
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: merge
        uses: roujiawang/action-automerge@v1
        id: merge
        with:
          source: 'develop'
          target: 'main'
