name: Hardcoded Merge Branch develop to main
on:
  push:
    branches:
      - develop
permissions:
  contents: write
  issues: write
jobs:
  merge-branch-dev-to-main:
    name: merge the develop branch into main
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{secrets.USER_NAME}}
      USER_EMAIL: ${{secrets.USER_EMAIL}}
      GITHUB_TOKEN: ${{secrets.SECRET_TOKEN}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: "develop"
      
      - name: merge branch dev to main
        run: |
          git config --global user.email "$USER_NAME"
          git config --global user.name "$USER_EMAIL"
          git config pull.rebase true # trigger rebase, not merge
          git fetch origin main --unshallow
          
          git checkout -b local_main
          git pull -X theirs --set-upstream origin main
          git merge develop -X theirs -m "merged origin develop into main"
          git push origin HEAD:main
          git branch --unset-upstream
          git branch -D local_main
