name: Hardcoded Merge Branch develop to main
on:
  push:
    branches:
      - develop
permissions:
  contents: write
  issues: write
jobs:
  merge-branch-dev-to-main:
    name: merge the develop branch into main
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{secrets.USER_NAME}}
      USER_EMAIL: ${{secrets.USER_EMAIL}}
      GITHUB_TOKEN: ${{secrets.SECRET_TOKEN}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: "main"
      
      - name: merge branch dev to main
        run: |
          git fetch origin develop --unshallow
          git checkout main
          git merge develop -m "merged origin develop into main"
