name: Hardcoded Merge Branch develop to main
on:
  push:
    branches:
      - develop
permissions:
  contents: write
  issues: write
jobs:
  merge-branch-dev-to-main:
    name: merge the develop branch into main
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{secrets.USER_NAME}}
      USER_EMAIL: ${{secrets.USER_EMAIL}}
      GITHUB_TOKEN: ${{secrets.SECRET_TOKEN}}
    steps:
      # this step is to avoid error: "not in a git directory"
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: "develop"
      
      - name: merge branch dev to main
        run: |
          git config --global user.email "$USER_NAME"
          git config --global user.name "$USER_EMAIL"
          git fetch origin main --unshallow # to edit it without limitations of shallow repo
          
          # configured to avoid error: "Need to specify how to reconcile divergent branches."
          # WARNING: may risk losing important edit history
          git config pull.rebase true # so that git pull triggers rebase, not merge
          
          # use a temp local branch to conduct merge
          # when git pull, settle conflicts in favor or main
          # when merge and push, settle conflicts in favor of dev
          git checkout -b local_main
          git pull -X theirs --set-upstream origin main
          git merge develop -X theirs -m "merged origin develop into main"
          git push origin HEAD:main
          
          # timely delete this temp local branch 
          git branch --unset-upstream
          git checkout main
          git branch -D local_main
